/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as ApiBootstrapRouteImport } from './routes/api.bootstrap'
import { Route as AuthenticatedRecordsIndexRouteImport } from './routes/_authenticated/records.index'
import { Route as AuthenticatedRecordsRecordIdRouteImport } from './routes/_authenticated/records.$recordId'
import { Route as AuthenticatedRecordsNewRouteImport } from './routes/_authenticated/records.new'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api.attachments.$attachmentId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as PrintRecordsRecordIdRouteImport } from './routes/print.records.$recordId'
import { Route as ApiRecordsRecordIdAttachmentsRouteImport } from './routes/api.records.$recordId.attachments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiBootstrapRoute = ApiBootstrapRouteImport.update({
  id: '/api/bootstrap',
  path: '/api/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecordsIndexRoute =
  AuthenticatedRecordsIndexRouteImport.update({
    id: '/records/',
    path: '/records/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecordsRecordIdRoute =
  AuthenticatedRecordsRecordIdRouteImport.update({
    id: '/records/$recordId',
    path: '/records/$recordId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecordsNewRoute = AuthenticatedRecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/api/attachments/$attachmentId',
    path: '/api/attachments/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRecordsRecordIdRoute = PrintRecordsRecordIdRouteImport.update({
  id: '/print/records/$recordId',
  path: '/print/records/$recordId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsRecordIdAttachmentsRoute =
  ApiRecordsRecordIdAttachmentsRouteImport.update({
    id: '/api/records/$recordId/attachments',
    path: '/api/records/$recordId/attachments',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/records/$recordId': typeof AuthenticatedRecordsRecordIdRoute
  '/records/new': typeof AuthenticatedRecordsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/print/records/$recordId': typeof PrintRecordsRecordIdRoute
  '/records/': typeof AuthenticatedRecordsIndexRoute
  '/api/records/$recordId/attachments': typeof ApiRecordsRecordIdAttachmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/records/$recordId': typeof AuthenticatedRecordsRecordIdRoute
  '/records/new': typeof AuthenticatedRecordsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/print/records/$recordId': typeof PrintRecordsRecordIdRoute
  '/records': typeof AuthenticatedRecordsIndexRoute
  '/api/records/$recordId/attachments': typeof ApiRecordsRecordIdAttachmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/api/bootstrap': typeof ApiBootstrapRoute
  '/_authenticated/records/$recordId': typeof AuthenticatedRecordsRecordIdRoute
  '/_authenticated/records/new': typeof AuthenticatedRecordsNewRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/print/records/$recordId': typeof PrintRecordsRecordIdRoute
  '/_authenticated/records/': typeof AuthenticatedRecordsIndexRoute
  '/api/records/$recordId/attachments': typeof ApiRecordsRecordIdAttachmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/directory'
    | '/api/bootstrap'
    | '/records/$recordId'
    | '/records/new'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/print/records/$recordId'
    | '/records/'
    | '/api/records/$recordId/attachments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/directory'
    | '/api/bootstrap'
    | '/records/$recordId'
    | '/records/new'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/print/records/$recordId'
    | '/records'
    | '/api/records/$recordId/attachments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/directory'
    | '/api/bootstrap'
    | '/_authenticated/records/$recordId'
    | '/_authenticated/records/new'
    | '/api/attachments/$attachmentId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/print/records/$recordId'
    | '/_authenticated/records/'
    | '/api/records/$recordId/attachments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiBootstrapRoute: typeof ApiBootstrapRoute
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  PrintRecordsRecordIdRoute: typeof PrintRecordsRecordIdRoute
  ApiRecordsRecordIdAttachmentsRoute: typeof ApiRecordsRecordIdAttachmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/bootstrap': {
      id: '/api/bootstrap'
      path: '/api/bootstrap'
      fullPath: '/api/bootstrap'
      preLoaderRoute: typeof ApiBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/records/': {
      id: '/_authenticated/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof AuthenticatedRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records/$recordId': {
      id: '/_authenticated/records/$recordId'
      path: '/records/$recordId'
      fullPath: '/records/$recordId'
      preLoaderRoute: typeof AuthenticatedRecordsRecordIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/records/new': {
      id: '/_authenticated/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof AuthenticatedRecordsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/api/attachments/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/records/$recordId': {
      id: '/print/records/$recordId'
      path: '/print/records/$recordId'
      fullPath: '/print/records/$recordId'
      preLoaderRoute: typeof PrintRecordsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$recordId/attachments': {
      id: '/api/records/$recordId/attachments'
      path: '/api/records/$recordId/attachments'
      fullPath: '/api/records/$recordId/attachments'
      preLoaderRoute: typeof ApiRecordsRecordIdAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedRecordsRecordIdRoute: typeof AuthenticatedRecordsRecordIdRoute
  AuthenticatedRecordsNewRoute: typeof AuthenticatedRecordsNewRoute
  AuthenticatedRecordsIndexRoute: typeof AuthenticatedRecordsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedRecordsRecordIdRoute: AuthenticatedRecordsRecordIdRoute,
  AuthenticatedRecordsNewRoute: AuthenticatedRecordsNewRoute,
  AuthenticatedRecordsIndexRoute: AuthenticatedRecordsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiBootstrapRoute: ApiBootstrapRoute,
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  PrintRecordsRecordIdRoute: PrintRecordsRecordIdRoute,
  ApiRecordsRecordIdAttachmentsRoute: ApiRecordsRecordIdAttachmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
